version: '3.8'

services:
  yield_web:
    build: .
    ports:
      - "3001:80"
    deploy:
      mode: replicated
      replicas: 1 # figure out a way to do sticky sessions with docker swarm to increase replicas
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'  # Limit to 2 CPU
        reservations:
          cpus: '0.5'  # Reserve 0.5 CPU  


