export const USER = "USER";
export const SAVINGS = "SAVINGS";
export const SAVINGS_TRANSACTIONS = "SAVINGS_TRANSACTIONS";
export const SAVINGS_PRODUCT_INFORMATION = "SAVINGS_PRODUCT_INFORMATION";
export const SAVINGS_CALCULATOR = "SAVINGS_CALCULATOR";
