export type User = {
  id: number;
  avatar: string;
  token: string;
  userId: number;
  is_new_device: boolean;
  nin: string;
  firstname: string;
  lastname: string;
  middlename: string;
  mobileNo: string;
  email: string;
  bvn: string;
  dateOfBirth: string;
  typeId: 38;
  addressLine1: string;
  stateProvinceId: string;
  preferred_number: string;
  preffered_notification_channel: string;
  kycLevel: number;
  gender: string;
  clientId: number;
  displayName: string;
  genderId: number;
  login_expiry: string;
  alternate_number: string;
  address_details: {
    addressType: string;
    isActive: boolean;
    addressLine1: string;
    stateProvinceId: number;
    stateName: string;
    countryId: number;
  }[];
  kyc_validation_details: {
    is_bvn_validated: boolean;
    is_nin_validated: boolean;
    is_client_identifier_validated: boolean;
    is_mobile_no_validated: boolean;
    is_email_validated: boolean;
    is_selfie_validated: boolean;
    is_adddress_validated: boolean;
  };
  kyc_validation: {
    basic: boolean;
    nin: boolean;
    bank: boolean;
    alternateNumber: boolean;
  };
  bank_details: {
    bankId: number;
    accountnumber: string;
    accountname: string;
    active: boolean;
    account_type: string;
    bank_classification: string;
  };
  // id: number;
  client_id: string;
  tier_level: string;
  is_active: boolean;
  login_2fa: boolean;
  is_2fa: boolean;
  is_suspended: boolean;
  // firstname: string;
  // lastname: string;
  // email: string;
  phone: string;
  encrypted_pin: string;
  tin: string | null;
  referal_code: string | null;
  // alternate_number: string;
  channel: string;
  is_phone_verified: boolean;
  is_alternate_number_verified: boolean;
  is_email_verified: boolean;
  is_bvn_verified: boolean;
  is_nin_verified: boolean;
  is_admin: boolean;
  onboarding_stage: string;
  cba_wallet_id: string;
  cba_flex_id: string;
  // preferred_number: string;
  preferred_notification_channel: string;
  created_at: string;
  updated_at: string;
  transaction_limit: string;
  deactivation_logs: Array<any>;
  zeusKycLevel: number;

  isAuthenticated: boolean;
  expiresIn: string;
  refreshToken: string;
};
