apiVersion: apps/v1
kind: Deployment
metadata:
  name: yield-app
  namespace: zeus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yield-app
  template:
    metadata:
      labels:
        app: yield-app
    spec:
      serviceAccount: application-sa
      containers:
      - name: yield-container
        image: {{IMAGE_TAG}}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2Gi"  # Ensure memory requests are at least 2GB
            cpu: "1000m"
          limits:
            memory: "4Gi"  # Allow up to 4GB memory
            cpu: "2000m"